import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cache } from "react";
import Image from "next/image";
import Link from "next/link";
import { client } from "./lib/contentful";
import "./globals.css";
import Footer from '@/components/Footer';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// cache() dedupes this so generateMetadata + RootLayout share one API call per request
const getSiteSettings = cache(async () => {
  const res = await client.getEntries({
    content_type: "siteSettings",
    locale: "en-US",
    limit: 1,
  });
  return res.items[0]?.fields as any;
});

export async function generateMetadata(): Promise<Metadata> {
  const settings = await getSiteSettings();
  const logoUrl = settings?.logo?.fields?.file?.url
    ? "https:" + settings.logo.fields.file.url
    : undefined;

  return {
    title: settings?.siteName || "Automation Anywhere",
    description: "Generated by create next app",
    icons: settings?.favicon?.fields?.file?.url
      ? { icon: "https:" + settings.favicon.fields.file.url }
      : undefined,
    openGraph: logoUrl ? { images: [logoUrl] } : undefined,
  };
}

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const settings = await getSiteSettings();
  const logoUrl = settings?.logo?.fields?.file?.url
    ? "https:" + settings.logo.fields.file.url
    : null;

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="border-b border-gray-200 site-header">
          <nav className="max-w-6xl mx-auto px-4 py-4 flex items-center justify-between">
            <Link href="/">
              {logoUrl ? (
                <Image
                src={logoUrl}
                alt={settings?.siteName || 'Automation Anywhere'}
                width={160}
                height={40}
                style={{ width: 'auto', height: 'auto' }}
                priority
              />
              ) : (
                <span className="font-bold text-lg">Automation Anywhere</span>
              )}
            </Link>
            <div className="flex gap-6 text-sm font-semibold text-gray-700">
              <Link href="#">Solutions</Link>
              <Link href="#">Products</Link>
              <Link href="/company/press-room">Press Room</Link>
              <Link href="/company/blog">Blog</Link>
            </div>
          </nav>
        </header>
        <main className="flex-1">{children}</main>
        
        <Footer logoUrl={logoUrl} siteName={settings?.siteName} />      </body>
    </html>
  );
}